"   _     _____ _____                 
"  | |   |  ___|  _  |                
"  | |   | |__ | | | |  ___           
"  | |   |  __|| | | | / __|          
"  | |___| |___\ \_/ / \__ \          
"  \_____|____/ \___/  |___/          
"   _   _ ________  ___ ______  _____ 
"  | | | |_   _|  \/  | | ___ \/  __ \
"  | | | | | | | .  . | | |_/ /| /  \/
"  | | | | | | | |\/| | |    / | |    
"  \ \_/ /_| |_| |  | | | |\ \ | \__/\
"   \___/ \___/\_|  |_/ \_| \_| \____/
"                                     
" Also known as ride_faster, drive_hard & .asm
"
" ====================

" START Vundle
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'VundleVim/Vundle.vim'
Plugin 'scrooloose/nerdtree'
Plugin 'fatih/vim-go'
Plugin 'stamblerre/gocode', {'rtp': 'vim/'}
Plugin 'zchee/deoplete-go'
Plugin 'dracula/vim'
Plugin 'shougo/deoplete.nvim'
Plugin 'roxma/nvim-yarp'
Plugin 'roxma/vim-hug-neovim-rpc'
Plugin 'vim-airline/vim-airline-themes'
call vundle#end()
" END   Vundle

" ====================

" START GO
let g:go_highlight_types = 1
let g:go_highlight_functions = 1
let g:go_highlight_function_calls = 1
let g:go_highlight_methods = 1
let g:go_highlight_operators = 1
let g:go_highlight_fields = 1
let g:go_highlight_structs = 1
let g:go_highlight_interfaces = 1
let g:go_highlight_build_constraints = 1
let g:go_fmt_command = "goimports"
" END   GO

" ====================

" START tabs
"" Spaces > Tabs
"" show existing tab with 4 spaces width
set tabstop=4
"" when indenting with '>', use 4 spaces width
set shiftwidth=4
"" On pressing tab, insert 4 spaces
set expandtab
" END   Tabs

" ====================

" START autocomplete
let g:deoplete#enable_at_startup = 1
" END   autocomplete

" ====================

" START NerdTree
"" open nerdtree on startup
"" Control+N
map <C-n> :NERDTreeToggle<CR>
"" Quit on open
let NERDTreeQuitOnOpen = 1
"" Remove buffer on delete
let NERDTreeAutoDeleteBuffer = 1
"" UI
let NERDTreeMinimalUI = 1
let NERDTreeDirArrows = 1
" END   NERDTREE

" ====================

" START Powerline
" Theme
let g:airline_theme='minimalist'
" Tabline
let g:airline#extensions#tabline#enabled = 1
" END   PowerLine

" ====================

" START The Normies
set number
syntax on
filetype plugin indent on
set nocompatible
set ruler
set tabstop=4
" END   The Normies

" ====================

" START Colors
"" Display tabs + color
set list
set listchars=tab:.\  
highlight SpecialKey ctermfg=black
"" Termcolors
set t_Co=256
set background=dark
let base16colorspace=256
colorscheme bluewery
highlight Normal ctermbg=NONE
highlight nonText ctermbg=NONE
" END   Colors
